name: pages-publish-master

on:
  push:
    branches:
      - hexo # default branch

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish to master
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          full_commit_message: hexo update
          publish_dir: ./public
      - name: Trigger my Webhookd
        uses: CamiloGarciaLaRotta/watermelon-http-client@v1
        with:
          url: https://hook.yuhenabc.com/hooks/io
